config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#index"
  resources :users
  resources :tasks
  get "/styles.css", to: "static#styles"
  post "some_action", to: "some#some_action"
  post "search", to: "some#search"
  get "index", to: "some#index"

  get "/terms_of_service", to: "static_pages#terms_of_service"
  get "/privacy_policy", to: "static_pages#privacy_policy"
end

app/views/shared/_footer.html.erb
<footer class="border-gray-200 px-4 lg:px-6 py-2.5 bg-base-300 dark:bg-gray-700 text-gray-800 dark:text-white">
  <div class="flex justify-start items-center">
    <nav class="flex space-x-4">
      <%= link_to "お問い合わせ", 'https://forms.gle/jenqvLbAnjxfaY9q9', class: "hover:bg-base-100 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 focus:outline-none" %>
      <%= link_to "プライバシーポリシー", "privacy_policy", class: "hover:bg-base-100 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 focus:outline-none" %>
      <%= link_to "利用規約", "terms_of_service", class: "hover:bg-base-100 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 focus:outline-none" %>
    </nav>
  </div>
  <aside class="text-sm text-center mt-4">
    <p>Copyright © 2024.こどもとどこいく？</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<header class="w-full navbar bg-base-300">
  <div class="flex items-center w-full">
    <div class="flex-1 px-2">
      <li><%= link_to 'ホーム', root_path, class: "text-lg font-bold text-orange-500"  %>
    </div> 
    <% if current_user %>
      <div class="flex">
        <li><%= link_to '投稿一覧', '#' %></li>
        <li><%= link_to 'マイページ', '#' %></li>
        <li><%= link_to 'ログアウト', '#' %></li>
      </div>
    <% else %>
      <div class="flex">
        <li><%= link_to 'ログイン', tasks_path %></li>
        <li><%= link_to '新規登録', new_user_path %></li>
      </div>
    <% end %>
  </div>
</header>